### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [SYtor/WifiPass#1]
Glad to see you've picked up development of this app again! Did you meanwhile decide what license your app is protected by? I find no pointer anywhere.

**Comment by syt0r** [comment]
Totally forgot about this, thanks for reminding. I've updated master branch with license

**Comment by IzzySoft** [comment]
Thought it must have "slipped through" :smile: Thanks for adding that quickly!

PS: I've just added as well: your app will [show up here](https://apt.izzysoft.de/fdroid/index/apk/ua.sytor.wifipass) in about 6 hours (with the next sync) and update within 24h of your adding a new tag with an APK attached. If you want to link there (people can use the F-Droid client to grab it from there and keep it up-to-date), be welcome to [use this badge](https://gitlab.com/IzzyOnDroid/repo#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it). If you want anything changed there (description etc), just let me know.
