### ISSUE TITLE
Android 11 - not working

### ISSUE THREAD

**Issue by SynapseScribe** [SYtor/WifiPass#5]
Is this supposed to work on android 11? I get error "configuration file not found"

**Comment by syt0r** [comment]
Unfortunately I couldn't find any way of retrieving passwords on android 11, configuration files that I've used to get this data from are empty on my device, so currently it's not supported

**Comment by Sahillove12** [comment]
Is this supposed to work on android 11? I get error "configuration file not found"

**Comment by Sahillove12** [comment]
Is this supposed to work on android 10? I get error "configuration file not found

**Comment by MuntashirAkon** [comment]
They're now moved to `/data/misc/apexdata/com.android.wifi/WifiConfigStore.xml`

**Comment by SynapseScribe** [comment]
> They're now moved to `/data/misc/apexdata/com.android.wifi/WifiConfigStore.xml`

woa you're the best. btw thanks for AM app. big fan

So can this app be modified to parse this file?

**Comment by ghost** [comment]
> So can this app be modified to parse this file?

Try this: [_Link removed by 7stripes._]
Forked from current master, added new Wi-Fi password location "/data/misc/apexdata/com.android.wifi/WifiConfigStore.xml".
All credit to syt0r.

**Comment by SynapseScribe** [comment]
Thank you 7stripes. Maybe it would be better to create a pull request under this repo, to be approved by syt0r

**Comment by ghost** [comment]
> Thank you 7stripes. Maybe it would be better to create a pull request under this repo, to be approved by syt0r

Done!
I didn't want to step on any toes and certainly don't want to take any credit. I just needed a working app for my own personal use and decided to share it here as it looked like you were looking for a working, updated version, too.
I hope I've created the pull request correctly (I'm a GitHub noob).

**Comment by SynapseScribe** [comment]
Can we have a new release in github? Also it would be nice to have it in playstore, and more importantly in f-droid/izzyondroid.

**Comment by syt0r** [comment]
Created v3.0 release, hopefully update covers all Android 11 devices. If not feel free to reopen the issue

**Comment by SynapseScribe** [comment]
On android 12 also not working. That config file doesn't seem to store passwords anymore
